### ISSUE TITLE
Esto es lo último, antes de entregar - Dar unidad a todo con CSS

### ISSUE THREAD

**Issue by gonzalonf** [gonzalonf/trabajo-integrador#10]
- [x] LOGIN Modificar tipografía/CAPS de 
- [x] LOGIN Modificar colores un poco
- [ ]  elegir foto/video final
- [x] **Unificar aspecto de todos los input** (no hay uno igual)
